---
title: "Coral"
author: "Callie Stephenson"
date: "2023-08-29"
output: github_document
---
### Introduction

This is a R Markdown file in which I hope to write out my analyses. I will use this document to process all the R scripts found in the R folder and complete my project. 

#### Loading the data
```{r install packages, echo=FALSE}
library(tidyverse)
library(here)
library(ggrepel)
library(patchwork)
library(tidytext)
library(AICcmodavg)
library(kableExtra)
library(PNWColors)
library(fishualize)
library(lme4)
library(ggpp)
library(ggplot2)
```
```{r load data, echo=FALSE}
nut <- read.csv("data/March_nutrients_processed.csv")
BW <- read.csv("data/BW_tidy.csv")
TLE <- read.csv("data/TLE_summary.csv")
FCM <- read.csv("output/FCM_data.csv")
```

# Buoyant Weight:
## Look for Outliers
```{r BW Pru, echo=FALSE}


```



FCM Data Analysis:
```{r}
nut <- read.csv("data/March_nutrients_processed.csv")
FCM <- read.csv("output/FCM_data.csv")
ggplot(FCM)+
  geom_point(aes(x=Cage_Uncaged, y=sym_FSC.Events, color=Species))

ggplot(FCM)+
  geom_boxplot(aes(x=Cage_Uncaged, y=sym_FSC.Events, color = Species))
```

```{r, warning=FALSE, message=FALSE}
FCM$CowTagID <- paste0("V",FCM$Pin_Number) #make a joining variable
all_data <- left_join(FCM, nut, by="CowTagID")  #join them
all_data <- drop_na(all_data)

m1 <- lm(sym_FSC.Events ~ log(Maximum), data= all_data %>%
           filter(Parameters=="Silicate_umolL"))
anova(m1)
summary(m1)

max <- all_data %>% 
       filter(Parameters=="Silicate_umolL")

hist(max$Maximum)
```

