
```{r packages, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(fishualize)
library(GGally) #function ggpairs()
library(arm)
library(car)
library(MASS) #model glm.nb for negbin
library(ggeffects)
library(gridExtra) #worked when cowplot failed me
library(effects)
library(grid) #for as.grob
```

```{r tidy data, warning=FALSE}
setwd("/Users/calliestephenson/Documents/GitHub/MooreaCoralFish_CS")
#nut <- read.csv("data/March_nutrients_processed.csv")
nut <- read.csv("data/Wet_Nutrients_Processed.csv")
all_nut <- read.csv("data/Nutrients_Processed_All.csv")
shore_dist <- read.csv("https://raw.githubusercontent.com/dbarnas/Community_Functional_Diversity/main/Data/Shore_distance.csv") #using Danielle's
seep_dist <- read.csv("https://raw.githubusercontent.com/dbarnas/Community_Functional_Diversity/main/Data/Plate_Distance_to_Seep.csv")
depth <- read.csv("https://raw.githubusercontent.com/njsilbiger/MooreaSGD_site-selection/main/Data/Adj_Sandwich_Depth.csv")
clod <- read.csv("data/Clod_Cards.csv")
```
```{r}
clod$CowTagID <- paste0("V",clod$PIN)
clod <- clod[,c(13,11)]

depth <- depth[,c(1,2,6)]
shore_dist <- left_join(shore_dist, seep_dist, by ="CowTagID")
shore_dist <- left_join(shore_dist, depth, by = "CowTagID")

#nut_wide <- pivot_wider(
#  data = nut,
#  names_from = Parameters,
#  values_from = 3:9,
#  names_glue = "{.value}_{Parameters}"
#)
#nut_wide_no_seep <- nut_wide[nut_wide$CowTagID != 'VSEEP', ]
nut_no_seep <- nut[nut$CowTagID != 'VSEEP',]

minimum_columns <- names(nut)[grepl("Minimum_", names(nut)) & 
                                     grepl("Salinity|Temperature|pH", names(nut))]
maximum_columns <- names(nut)[grepl("Maximum_", names(nut)) & 
                                  !grepl("Salinity|Temperature|pH|Ammonia_umol",names(nut))]
mean_columns <- names(nut)[grepl("Mean_", names(nut)) & 
                                  !grepl("Salinity|Temperature|pH|Ammonia_umol",names(nut))]
CV_columns <- names(nut)[grepl("CV_", names(nut), names(nut))]

pulse_columns <- names(nut)[grepl("Low_Tide_Mean_", names(nut)) & 
                                  !grepl("Salinity|Temperature|pH|Ammonia_umol",names(nut))]

meta_columns <- names(nut_no_seep)[c(1)]

#keeping V13 in this ex
```

```{r}
#all_nut_wide <- pivot_wider(
#  data = all_nut,
#  names_from = Parameters,
#  values_from = 7:13,
#  names_glue = "{.value}_{Parameters}"
#)

#all_nut_wide <- all_nut_wide %>% 
#  filter(Location == "Varari")

#nut_wide_no_seep <- nut_wide[nut_wide$CowTagID != 'VSEEP', ]

#minimum_columns <- names(nut_wide)[grepl("Minimum_", names(nut_wide)) & 
#                                     grepl("Salinity|Temperature|pH", names(nut_wide))]
#maximum_columns <- names(nut_wide)[grepl("Maximum_", names(nut_wide)) & 
#                                  !grepl("Salinity|Temperature|pH|Ammonia_umol",names(nut_wide))]
#mean_columns <- names(nut_wide)[grepl("MeanSeasonal_", names(nut_wide)) & 
#                                  !grepl("Salinity|Temperature|pH|Ammonia_umol",names(nut_wide))]
#CV_columns <- names(nut_wide)[grepl("CVSeasonal_", names(nut_wide), names(nut_wide))]
#meta_columns <- names(nut_wide_no_seep)[c(1:6)]



#pca.data <- na.omit(nut_wide_no_seep[, c(maximum_columns, minimum_columns, mean_columns, CV_columns)])
```


###PCA
```{r pca with max, min, cv}
pca.data <- na.omit(nut_no_seep[, c(maximum_columns, 
                                    minimum_columns,
#                                    mean_columns, #removed bc not enough data for the amount of variables
                                    CV_columns)])
pca = princomp(pca.data, cor=TRUE)
summary(pca)
```
```{r loadings for 1 pca}
loadings(pca)
```

```{r biplot 1 pca}
biplot(pca, col = c('grey', 'blue'))
```

```{r adding values to nut no seep}
nut_no_seep$pc1 = pca$scores[,1] #what's this data's score on pc1 axis
nut_no_seep$pc2 = pca$scores[,2] #what's this data's score on pc2 axis
```


Megan wants me to 'take the loadings onto pc1'
make a "cheap map" that plots lat long and colors by pc1
```{r make map of pca values for axes 1 and 2}
#editing nutwidenoseep so that i also now have clod card data and shore dist data as columns
nut_no_seep <- left_join(nut_no_seep, clod) 
nut_no_seep <- left_join(nut_no_seep, seep_dist[,c("CowTagID", "lat", "lon", "dist_to_seep_m")])
nut_no_seep <- left_join(nut_no_seep, shore_dist[,c("CowTagID", "shore_dist_m")])

ggplot(nut_no_seep, aes(x = lon, y = lat, color = pc1)) +
  geom_point() +
  labs(x = "Latitude", y = "Longitude", color = "PC1") +
  scale_color_fish(option = "Coryphaena_hippurus", direction = -1) +
  theme_minimal()
```

Should I incorporate shore dist? Shore dist might be linear with these nutrients, if it isn't, it's better to put into the models as a separate variable.
```{r PCA vs Shore Dist, warning=FALSE}
ggpairs(na.omit(nut_no_seep)[c("pc1", "pc2", "shore_dist_m", "dist_to_seep_m")], progress = FALSE)
```


```{r write nut no seep as csv}
nut_no_seepa <- nut_no_seep[, c(meta_columns,maximum_columns, minimum_columns, mean_columns, CV_columns,"pc1","pc2","X._loss", "lat","lon","dist_to_seep_m","shore_dist_m")]
explanatory2 <- pivot_longer(
  data = nut_no_seepa,
  cols = c(Maximum_TA:pc2)) 
names(explanatory2)[names(explanatory2) == "name"] <- "Parameter"
#write.csv(explanatory2,"Explanatory_variables.csv")
```

```{r PCA for CV columns}
pca.data <- na.omit(nut_no_seep[, c(#maximum_columns, 
                                    #minimum_columns,
#                                    mean_columns, #removed bc not enough data for the amount of variables
                                    CV_columns)])
pca = princomp(pca.data, cor=TRUE)
summary(pca)
loadings(pca)
```

```{r biplot cv pca}
biplot(pca)
```

```{r}
nut_no_seep$cvpc1 = pca$scores[,1] #what's this data's score on pc1 axis
nut_no_seep$cvpc2 = pca$scores[,2] #what's this data's score on pc2 axis

ggplot(nut_no_seep, aes(x = lon, y = lat, color = cvpc1)) +
  geom_point() +
  labs(x = "Latitude", y = "Longitude", color = "PC1") +
  scale_color_fish(option = "Coryphaena_hippurus", direction = -1) +
  theme_minimal()
```


## TRYING A MEAN LOW PCA:

```{r mean low PCA}
pca.data <- na.omit(nut_no_seep[, c(pulse_columns)])
pca = princomp(pca.data, cor=TRUE)
summary(pca)
```

```{r loadings pulse pca}
loadings(pca)
```

```{r biplot pulse pca}
biplot(pca, col = c('grey', 'blue'))
```

```{r}
nut_no_seep$pulse_pc1 = pca$scores[,1] #what's this data's score on pc1 axis
nut_no_seep$pulse_pc2 = pca$scores[,2] #what's this data's score on pc2 axis

plot1 <- ggplot(nut_no_seep, aes(x = lon, y = lat, color = pulse_pc1)) +
  geom_point() +
  labs(x = "Latitude", y = "Longitude", color = "PC1") +
  scale_color_fish(option = "Coryphaena_hippurus", direction = -1) +
  theme_minimal()

plot2 <- ggplot(nut_no_seep, aes(x = lon, y = lat, color = pulse_pc1)) +
  geom_point() +
  labs(x = "Latitude", y = "Longitude", color = "PC2") +
  scale_color_fish(option = "Coryphaena_hippurus", direction = -1) +
  theme_minimal()

grid.arrange(plot1, plot2, ncol = 2)
```

```{r REWRITING Explanatory_variables}
nut_no_seepa <- nut_no_seep[, c(meta_columns,maximum_columns, minimum_columns, mean_columns, CV_columns,pulse_columns, "pc1","pc2","X._loss", "lat","lon","dist_to_seep_m","shore_dist_m", "pulse_pc1", "pulse_pc2")]
explanatory2 <- pivot_longer(
  data = nut_no_seepa,
  cols = c(Maximum_TA:pulse_pc2)) 
names(explanatory2)[names(explanatory2) == "name"] <- "Parameter"
#write.csv(explanatory2,"Explanatory_variables.csv")
#write.csv(nut_no_seepa,"Explanatory_variables_wide.csv")
```

